[2024-09-22T13:33:44.880+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-22T13:33:44.889+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: project.process_user manual__2024-09-22T12:57:24.010523+00:00 [queued]>
[2024-09-22T13:33:44.893+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: project.process_user manual__2024-09-22T12:57:24.010523+00:00 [queued]>
[2024-09-22T13:33:44.893+0000] {taskinstance.py:2865} INFO - Starting attempt 4 of 4
[2024-09-22T13:33:44.900+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): process_user> on 2024-09-22 12:57:24.010523+00:00
[2024-09-22T13:33:44.905+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5901) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-22T13:33:44.907+0000] {standard_task_runner.py:72} INFO - Started process 5903 to run task
[2024-09-22T13:33:44.910+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'project', 'process_user', 'manual__2024-09-22T12:57:24.010523+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/project.py', '--cfg-path', '/tmp/tmp5klzgfar']
[2024-09-22T13:33:44.912+0000] {standard_task_runner.py:105} INFO - Job 33: Subtask process_user
[2024-09-22T13:33:44.937+0000] {task_command.py:467} INFO - Running <TaskInstance: project.process_user manual__2024-09-22T12:57:24.010523+00:00 [running]> on host 0bbd6d2129ab
[2024-09-22T13:33:44.991+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='project' AIRFLOW_CTX_TASK_ID='process_user' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T12:57:24.010523+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-22T12:57:24.010523+00:00'
[2024-09-22T13:33:44.992+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-22T13:33:44.993+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-22T13:33:44.993+0000] {logging_mixin.py:190} INFO - Current task name:process_user state:running start_date:2024-09-22 13:33:44.889903+00:00
[2024-09-22T13:33:44.993+0000] {logging_mixin.py:190} INFO - Dag name:project and current dag run status:running
[2024-09-22T13:33:44.993+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-22T13:33:45.000+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/project.py", line 13, in _process_user
    processed_user = json.loads(user)
                     ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
[2024-09-22T13:33:45.006+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-22T13:33:45.006+0000] {logging_mixin.py:190} INFO - Task start:2024-09-22 13:33:44.889903+00:00 end:2024-09-22 13:33:45.005942+00:00 duration:0.116039
[2024-09-22T13:33:45.006+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): process_user> dag:<DAG: project> dagrun:<DagRun project @ 2024-09-22 12:57:24.010523+00:00: manual__2024-09-22T12:57:24.010523+00:00, state:running, queued_at: 2024-09-22 13:33:40.899381+00:00. externally triggered: True>
[2024-09-22T13:33:45.006+0000] {logging_mixin.py:190} INFO - Failure caused by the JSON object must be str, bytes or bytearray, not dict
[2024-09-22T13:33:45.007+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=project, task_id=process_user, run_id=manual__2024-09-22T12:57:24.010523+00:00, execution_date=20240922T125724, start_date=20240922T133344, end_date=20240922T133345
[2024-09-22T13:33:45.013+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-22T13:33:45.013+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 33 for task process_user (the JSON object must be str, bytes or bytearray, not dict; 5903)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/project.py", line 13, in _process_user
    processed_user = json.loads(user)
                     ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
[2024-09-22T13:33:45.050+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-22T13:33:45.066+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-22T13:33:45.067+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
