[2024-09-23T14:48:13.108+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-23T14:48:13.119+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 008-simple-extract-load-bq.check_row_count manual__2024-09-23T11:32:25.296554+00:00 [queued]>
[2024-09-23T14:48:13.123+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 008-simple-extract-load-bq.check_row_count manual__2024-09-23T11:32:25.296554+00:00 [queued]>
[2024-09-23T14:48:13.124+0000] {taskinstance.py:2865} INFO - Starting attempt 10 of 10
[2024-09-23T14:48:13.133+0000] {taskinstance.py:2888} INFO - Executing <Task(BigQueryValueCheckOperator): check_row_count> on 2024-09-23 11:32:25.296554+00:00
[2024-09-23T14:48:13.140+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2282) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-23T14:48:13.141+0000] {standard_task_runner.py:72} INFO - Started process 2290 to run task
[2024-09-23T14:48:13.143+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '008-simple-extract-load-bq', 'check_row_count', 'manual__2024-09-23T11:32:25.296554+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/008-simple-extract-load-bq.py', '--cfg-path', '/tmp/tmpl1irmgv3']
[2024-09-23T14:48:13.145+0000] {standard_task_runner.py:105} INFO - Job 144: Subtask check_row_count
[2024-09-23T14:48:13.191+0000] {task_command.py:467} INFO - Running <TaskInstance: 008-simple-extract-load-bq.check_row_count manual__2024-09-23T11:32:25.296554+00:00 [running]> on host 49bf9bae52f3
[2024-09-23T14:48:13.242+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='008-simple-extract-load-bq' AIRFLOW_CTX_TASK_ID='check_row_count' AIRFLOW_CTX_EXECUTION_DATE='2024-09-23T11:32:25.296554+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-23T11:32:25.296554+00:00'
[2024-09-23T14:48:13.244+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-23T14:48:13.245+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-23T14:48:13.245+0000] {logging_mixin.py:190} INFO - Current task name:check_row_count state:running start_date:2024-09-23 14:48:13.119595+00:00
[2024-09-23T14:48:13.245+0000] {logging_mixin.py:190} INFO - Dag name:008-simple-extract-load-bq and current dag run status:running
[2024-09-23T14:48:13.246+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-23T14:48:13.246+0000] {baseoperator.py:405} WARNING - BigQueryValueCheckOperator.execute cannot be called outside TaskInstance!
[2024-09-23T14:48:13.246+0000] {sql.py:863} INFO - Executing SQL check: SELECT COUNT(*) FROM astronomer.forestfires
[2024-09-23T14:48:13.289+0000] {base.py:84} INFO - Retrieving connection 'bigquery'
[2024-09-23T14:48:13.357+0000] {sql.py:509} INFO - Running statement: SELECT COUNT(*) FROM astronomer.forestfires, parameters: None
[2024-09-23T14:48:13.359+0000] {bigquery.py:1702} INFO - Inserting job ***_1727102893358803_9d9b418343b00f30a3c623e2fb88de33
[2024-09-23T14:48:15.443+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 447, in execute
    super().execute(context=context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 865, in execute
    self.check_value(records)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 860, in check_value
    self._raise_exception(error_msg)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 182, in _raise_exception
    raise AirflowException(exception_string)
airflow.exceptions.AirflowException: Test failed.
Pass value:9.0
Tolerance:None
Query:
SELECT COUNT(*) FROM astronomer.forestfires
Results:
[10]
[2024-09-23T14:48:15.446+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-23T14:48:15.447+0000] {logging_mixin.py:190} INFO - Task start:2024-09-23 14:48:13.119595+00:00 end:2024-09-23 14:48:15.446390+00:00 duration:2.326795
[2024-09-23T14:48:15.447+0000] {logging_mixin.py:190} INFO - Task:<Task(BigQueryValueCheckOperator): check_row_count> dag:<DAG: 008-simple-extract-load-bq> dagrun:<DagRun 008-simple-extract-load-bq @ 2024-09-23 11:32:25.296554+00:00: manual__2024-09-23T11:32:25.296554+00:00, state:running, queued_at: 2024-09-23 14:47:58.062284+00:00. externally triggered: True>
[2024-09-23T14:48:15.447+0000] {logging_mixin.py:190} INFO - Failure caused by Test failed.
Pass value:9.0
Tolerance:None
Query:
SELECT COUNT(*) FROM astronomer.forestfires
Results:
[10]
[2024-09-23T14:48:15.447+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=008-simple-extract-load-bq, task_id=check_row_count, run_id=manual__2024-09-23T11:32:25.296554+00:00, execution_date=20240923T113225, start_date=20240923T144813, end_date=20240923T144815
[2024-09-23T14:48:15.454+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-23T14:48:15.454+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 144 for task check_row_count (Test failed.
Pass value:9.0
Tolerance:None
Query:
SELECT COUNT(*) FROM astronomer.forestfires
Results:
[10]; 2290)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 447, in execute
    super().execute(context=context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 865, in execute
    self.check_value(records)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 860, in check_value
    self._raise_exception(error_msg)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 182, in _raise_exception
    raise AirflowException(exception_string)
airflow.exceptions.AirflowException: Test failed.
Pass value:9.0
Tolerance:None
Query:
SELECT COUNT(*) FROM astronomer.forestfires
Results:
[10]
[2024-09-23T14:48:15.473+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-23T14:48:15.486+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-23T14:48:15.487+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
